-- MySQL Script generated by MySQL Workbench
-- Mon Apr 28 10:35:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CookingClasses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CookingClasses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CookingClasses` DEFAULT CHARACTER SET utf8 ;
USE `CookingClasses` ;

-- -----------------------------------------------------
-- Table `CookingClasses`.`Participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CookingClasses`.`Participants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CookingClasses`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CookingClasses`.`places` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CookingClasses`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CookingClasses`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CookingClasses`.`cook_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CookingClasses`.`cook_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `begin_time_date` DATETIME NOT NULL,
  `finish_time_date` TIME NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `max_place` INT NOT NULL,
  `last_inscription` DATE NULL,
  `places_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cook_courses_places_idx` (`places_id` ASC) VISIBLE,
  INDEX `fk_cook_courses_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  CONSTRAINT `fk_cook_courses_places`
    FOREIGN KEY (`places_id`)
    REFERENCES `CookingClasses`.`places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cook_courses_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `CookingClasses`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CookingClasses`.`Participants_has_cook_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CookingClasses`.`Participants_has_cook_courses` (
  `Participants_id` INT NOT NULL,
  `cook_courses_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `Participants_id`, `cook_courses_id`),
  INDEX `fk_Participants_has_cook_courses_cook_courses1_idx` (`cook_courses_id` ASC) VISIBLE,
  INDEX `fk_Participants_has_cook_courses_Participants1_idx` (`Participants_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Participants_has_cook_courses_Participants1`
    FOREIGN KEY (`Participants_id`)
    REFERENCES `CookingClasses`.`Participants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_has_cook_courses_cook_courses1`
    FOREIGN KEY (`cook_courses_id`)
    REFERENCES `CookingClasses`.`cook_courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
