USE CookingClasses;

INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (1,'Jason Roger Marc','Edmonds', '0761234567', 'jason.edmonds@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (2,'Sofian','Hussein', '0762345678', 'sofian.hussein@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (3,'Loïc','Roux', '0763456789', 'loïc.roux@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (4,'Amil','Sabotic', '0764567890', 'amil.sabotic@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (5,'Rodrigo','Silva Riço', '0765678901', 'rodrigo.silva riço@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (6,'Milo','Soupper', '0766789012', 'milo.soupper@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (7,'Samuel','Theytaz', '0767890123', 'samuel.theytaz@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (8,'Samuel','Antunes', '0768901234', 'samuel.antunes@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (9,'Joel','Cunha Faria', '0769012345', 'joel.cunha faria@eduuvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (10,'Léo','Del Duca', '0760123456', 'léo.del duca@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (11,'Iago','Dolfini De Paula', '0799876543', 'iago.dolfini@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (12,'Dani','Dordevic', '0798765432', 'dani.dordevic@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (13,'Even','Gebregergs', '0797654321', 'even.gebregergs@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (14,'Antoine','Jaccard', '0796543210', 'antoine.jaccard@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (15,'Cédric','Jankiewicz', '0795432109', 'cédric.jankiewicz@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (16,'Oleksii','Kamarali', '0794321098', 'oleksii.kamarali@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (17,'Timmy','Marendaz', '0793210987', 'timmy.marendaz@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (18,'Dylan','Martini', '0792109876', 'dylan.martini@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (19,'Thierry','Perroud', '0791098765', 'thierry.perroud@eduvaud.ch');
INSERT INTO `participants` (id,first_name, last_name, phone, mail) VALUES (20,'Melva','Zerda Macias', '0781234567', 'melva.zerda macias@eduvaud.ch');